[package]
name = "receipt_issuer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
pbr = "1.0.4"
rust_decimal = "1.27.0"
rust_decimal_macros = "1.27.0"
